### ISSUE TITLE
problem on converting png with opacity

### ISSUE THREAD

**Issue by nicoZ33** [femtopixel/femtopixel.github.io#1]
if an opacity is present the pixels returned with this one are black

ex in :
![image](https://cloud.githubusercontent.com/assets/25814988/24461926/fca13f96-14a2-11e7-9c8e-21201fb49d69.png)

ex out :
![image](https://cloud.githubusercontent.com/assets/25814988/24461934/056f5fd6-14a3-11e7-96d6-6ecdd00dd36a.png)

**Comment by jaymoulin** [comment]
I think this is related to [femtopixel/crop](http://github.com/femtopixel/crop/issues) instead of this page!
